version: "3"

services:
  db:
    image: 'mongo'
    ports:
      - "27017:27017"
  app:
    build: .
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app
    depends_on:
      - db
